/*****************************************************************************
 **     SAKARYA ÜNİVERSİTESİ 
 **        BİLGİSAYAR VE BİLİŞİM BİLİMLERİ FAKÜLTESİ 
 **       NESNEYE DAYALI PROGRAMLAMA DERSİ 
 **     2019-2020 BAHAR DÖNEMİ 
 **
 **    ÖDEV NUMARASI..........: 1
 **    ÖĞRENCİ ADI............:Ahmed Gazihan Birincioğlu 
 **    ÖĞRENCİ NUMARASI.......:b191200004
 **    DERSİN ALINDIĞI GRUP...:
 ****************************************************************************/


using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.OleDb;
namespace Rehber
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }
        OleDbConnection baglanti = new OleDbConnection("Provider=Microsoft.ACE.OleDb.12.0; Data Source=Kisiler.accdb ");
        OleDbCommand komut = new OleDbCommand();
        OleDbDataReader dr;
        OleDbDataAdapter da;
        DataTable dt = new DataTable();
        int id;
        private void Bagla_Click(object sender, EventArgs e)
        {
            if (bagla.Text == "Düzenle") //eğer butonda düzenle yazıyorsa var olan bilgileri düzenlememizi sağlar
            {
                try
                {
                    baglanti.Open();
                    komut.Connection = baglanti;
                    komut.CommandText = "UPDATE Kisiler SET baslik='"+textBox1.Text+ "',numara='" + textBox2.Text + "',@adres='" + textBox3.Text + "' WHERE id=" + id;
                    komut.ExecuteNonQuery();
                    MessageBox.Show("kişi düzenlendi");
                   
                    list();
                }
                catch (Exception hata)
                {
                    MessageBox.Show(hata.Message.ToString());

                }
                finally
                {
                    baglanti.Close();

                }
                textBox1.Text = "";
                textBox2.Text = "";
                textBox3.Text = "";
                id = 0;
                bagla.Text = "Kişi Ekle";
            }
            else //eğer düzenle yazmıyorsa yeni kişi eklemeemizi sağlar
            {
                try
                {
                    baglanti.Open();
                    komut.Connection = baglanti;
                    komut.CommandText = "SELECT * FROM Kisiler WHERE numara=" + textBox2.Text;
                    dr = komut.ExecuteReader();
                    dr.Read();
                    if (dr.HasRows)
                    {
                        MessageBox.Show("bu numara kayıtlı"); //tekrar aynı numara girilmemesi için kontrol
                    }
                    else
                    {
                        komut.Dispose();
                        dr.Dispose();
                        komut.Connection = baglanti;
                        komut.CommandText = "INSERT INTO Kisiler(baslık,numara,@adres) VALUES('" + textBox1.Text + "','" + textBox2.Text + "','" + textBox3.Text + "')";
                        komut.ExecuteNonQuery();
                        MessageBox.Show("Kişi Eklendi"); //aynı numara girilmediyse kişiyi kaydeder
                    }

                }
                catch (Exception hata)
                {
                    MessageBox.Show(hata.Message.ToString());

                }
                finally
                {
                    baglanti.Close();
                    
                }
                bagla.Text = "Düzenle";
            }
            
            
            
           

        }

        private void label1_Click(object sender, EventArgs e)
        {
            // yanlışıkla bastım silince yada kapatınca sebepsiz yere arıza çıkarıyor
        }
        void list() //listede ekleme ve düzenleme yaparken kullanılan fonksiyon
        {
            if (baglanti.State == ConnectionState.Open)
                baglanti.Close();
            dt.Clear();
            try
            {
                baglanti.Open();
                komut.Connection = baglanti;
                komut.CommandText = "SELECT * FROM Kisiler";
                da = new OleDbDataAdapter(komut);
                da.Fill(dt);
                dataGridView1.DataSource = dt;
            }
            catch (Exception hata)
            {
                MessageBox.Show(hata.Message.ToString());

            }
            finally
            {
                baglanti.Close();

            }
        }
      void sil() //listeden birini silereken kullanılan fonksiyon
        {
            if (baglanti.State == ConnectionState.Open)
                baglanti.Close();
          
            try
            {
                if(id>0)
                {
                    baglanti.Open();
                    komut.Connection = baglanti;
                    komut.CommandText = "DELETE  FROM Kisiler WHERE id="+id;
                    komut.ExecuteNonQuery();
                    MessageBox.Show("kişi silindi");
                    list();
                }
                
            }
            catch (Exception hata)
            {
                MessageBox.Show(hata.Message.ToString());

            }
            finally
            {
                baglanti.Close();

            }
        }                                
       
        private void Form1_Load_1(object sender, EventArgs e) //listenin görünüm ayarları
        {
            list();
            dataGridView1.Columns[0].HeaderText = "ID";
            dataGridView1.Columns[1].HeaderText = "Baslık";
            dataGridView1.Columns[2].HeaderText = "Numara";
            dataGridView1.Columns[0].Width = 30;
            dataGridView1.Columns[1].Width = 90;
            dataGridView1.Columns[2].Width = 90;
        }

        private void dataGridView1_CellContentClick(object sender, DataGridViewCellEventArgs e) //tek tıkta düzenlemeye geçmemizi sağlayan komut
        {
            id = Convert.ToInt32(dataGridView1.CurrentRow.Cells[0].Value);
            textBox1.Text = dataGridView1.CurrentRow.Cells[1].Value.ToString();
            textBox2.Text = dataGridView1.CurrentRow.Cells[2].Value.ToString();
            textBox3.Text = dataGridView1.CurrentRow.Cells[3].Value.ToString();
            bagla.Text = "Düzenle";
        }

        private void dataGridView1_CellContentDoubleClick(object sender, DataGridViewCellEventArgs e) //çift tıkta silmemizi sağlayan komut
        {
            id = Convert.ToInt32(dataGridView1.CurrentRow.Cells[0].Value);
            sil();
        }
    }
}
